### ISSUE TITLE
FatalErrorException in ArticlesRepository.php line 6

### ISSUE THREAD

**Issue by yaneclev** [tonysm/laravel-elasticsearch-test#1]
FatalErrorException in ArticlesRepository.php line 6:
Default value for parameters with a class type hint can only be NULL
The code:
namespace App\Articles;
use Illuminate\Database\Eloquent\Collection;
interface ArticlesRepository
{
    public function search(string $query = ""): Collection;
}

**Comment by yaneclev** [comment]
<?php
namespace App\Articles;
use Illuminate\Database\Eloquent\Collection;
interface ArticlesRepository
{
    public function search(string $query = ""): Collection;
}

**Comment by tonysm** [comment]
This is probably due to your PHP version. Which version are you using to test this?

**Comment by yaneclev** [comment]
PHP 5.6.23 with Laravel 5.4.17

**Comment by tonysm** [comment]
yeah, this code runs on PHP 7.x. You can either update your php version, or remove the type hints from the code (port it to php 5.6). Here's an example:

https://github.com/madewithlove/laravel-elasticsearch-demo/blob/master/app/Articles/ArticlesRepository.php#L9

This would be:

```php
<?php

namespace App\Articles;

use Illuminate\Database\Eloquent\Collection;

interface ArticlesRepository
{
    public function search($query = "");
}
```

**Comment by yaneclev** [comment]
unfortunately didn't work, migrated to php7 and now in the step for migrate --seed I get the below error:


  [Illuminate\Database\QueryException]
  Array to string conversion (SQL: insert into "articles" ("title", "body", "tags", "updated_at", "created_at") values (Cum ducimus voluptatem eum
   rerum voluptatem quia consequatur., Similique ut non est. Aliquam quis error nesciunt veritatis. Doloribus aut est quibusdam veniam quibusdam e
  t magnam., php, 2017-04-14 17:11:31, 2017-04-14 17:11:31))

**Comment by yaneclev** [comment]
Tried to clone the repo and composer update gives me this error:
  [Elasticsearch\Common\Exceptions\InvalidArgumentException]
  Could not parse URI

Are you sure this should work?

**Comment by tonysm** [comment]
I've just cloned it here, it works. You should follow the blogpost though: https://blog.madewithlove.be/post/how-to-integrate-your-laravel-app-with-elasticsearch/

To make it work with cloning it from this repository, you need to have elasticsearch running on your localhost (like the article says) and then here's the commands:

```bash
cp .env.example .env
touch database/database.sqlite
```

Edit the `.env` file we just "created", with:

```
SEARCH_ENABLED=true
SEARCH_HOSTS=localhost
DB_CONNECTION=sqlite
```

Delete all the other `DB_*` keys from there.

Now you can run:

``` bash
composer install
yarn # or npm install
npm run dev
php artisan key:generate
php artisan migrate --seed
php artisan serve
```

Now you can go ahead and open [http://localhost:8000](http://localhost:8000) in your browser.

**Comment by tonysm** [comment]
I got PHP 7.1.4-1 here.

**Comment by tonysm** [comment]
Closing this.
